from .drivstoff.virkning import Drivstoff
from .investering.virkning import Investeringskostnader
from .kontantstrommer.virkning import Kontantstrommer
from .risiko.virkning import Risiko
from .sedimenter.virkning import Sedimenter
from .tid.virkning import Tidsbruk
from .utslipp_til_luft.virkning import Utslipp_til_luft
from .vedlikehold.virkning import Vedlikeholdskostnader
from .ventetid.virkning import Ventetid
