name: "Automatisk bygging av dokumentasjon"
on:
  push:
    branches:
      - FRAM3_5

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Copy requirements to docs folder
      run: |
        cp requirements.txt docs_source/
        cat requirements-dev.txt >> docs_source/requirements.txt
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs_source/"
    - name: Pull gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: Commit documentation changes
      run: |
        git config --global user.email github-actions@github.com
        git config --global user.name github-actions
        cp -r docs/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git add .
        git commit -m "Automatisk bygging av dokumentasjon" -a || true
        git push